### ISSUE TITLE
Postico crashes with CockroachDB 2.1 rc-1

### ISSUE THREAD

**Issue by awoods187** [jakob/Postico#600] opened 2018-10-25 14:53 UTC
https://github.com/cockroachdb/cockroach/issues/31834#issuecomment-433078215

CockroachDB used to work with Postico. 

We suspect that Postico now attempts to take advantage of Cockroach unique show columns instead of using Postgres standard. Postico should use the Postgres standard approach rather than CockroachDB specific implementation in this case.

**Comment by jordanlewis** [comment] 2018-10-25 14:57
A little more detail:

CockroachDB changed the schema of its `SHOW COLUMNS` output recently. Those commands should be viewed as "porcelain", not "plumbing", a la Git commands - their schemas might change from release to release.

Postico should stick with the ordinary Postgres way of determining things - use `pg_catalog`.

**Comment by jakob** [comment] 2018-10-28 21:03
Thanks for letting us know!

Unfortunately it's not as easy as disabling the special handling of CockroachDB, since Cockroach doesn't seem to support the queries we use to query pg_catalog.

Here's one of the queries that trips up CockroachDB if I remove the special handling:

```sql
SELECT
    pg_class.oid,
    pg_class.relname,
    indisunique,
    indisprimary,
    indisexclusion,
    indkey,
    pg_get_indexdef(indexrelid, 0, TRUE) AS definition,
    ARRAY (
        SELECT
            pg_get_indexdef(indexrelid, attnum, TRUE)
        FROM
            pg_attribute
        WHERE
            attrelid = indexrelid
        ORDER BY
            attnum) AS expressions,
        obj_description(pg_class.oid, 'pg_class') AS COMMENT,
        indoption,
        ARRAY (
            SELECT
                pg_collation.collname
            FROM
                unnest(indcollation) AS t (colid)
                LEFT JOIN pg_collation ON pg_collation.oid = colid) AS collations,
    ARRAY (
        SELECT
            pg_opclass.opcname
        FROM
            generate_series(0, indnatts - 1) AS t (i)
            LEFT JOIN pg_opclass ON pg_opclass.oid = indclass [ i ]) AS opclasses,
    pg_get_expr(indpred, indrelid, TRUE),
    amname
FROM
    pg_index
    LEFT JOIN pg_class ON pg_class.oid = indexrelid
    LEFT JOIN pg_am ON pg_class.relam = pg_am.oid
WHERE
    indrelid = '"public"."test"'::regclass
ORDER BY
    pg_class.oid;
```

We probably need to find a different way to write that query.

**Comment by RaduBerinde** [comment] 2018-10-29 15:26
The error for the query above (I replaced `indexrelid`, `indnatts`, `indcolation` with some bogus values): `virtual schema table not implemented: pg_catalog.pg_opclass`

**Comment by bobvawter** [comment] 2018-10-29 16:34
Tracking issue for `pg_opclass`: https://github.com/cockroachdb/cockroach/issues/27763

**Comment by jakob** [comment] 2018-10-29 17:38
I've now changed Postico to query `pg_catalog` instead of `SHOW COLUMNS` for CockroachDB, and I've made it a bit more resilient to schema changes (Postico really shouldn't crash for unexpected server inputs).

I've run our test suite against CockroachDB 2.0.0 and 2.1.0-rc.1. Everything looks good now.

(I see that the `'\' LIKE  '%\\%'` is finally fixed in CockroachDB 2.1 👍)

Please try this build: [postico-3700.zip](https://github.com/jakob/Postico/files/2526346/postico-3700.zip)

**Comment by vilterp** [comment] 2018-10-29 18:00
Works for me 👍 Thanks!

**Comment by aaronkramer** [comment] 2018-10-31 22:14
Confirmed - this build works for me also

**Comment by RaduBerinde** [comment] 2018-10-31 22:16
> (I see that the `'\' LIKE '%\\%'` is finally fixed in CockroachDB 2.1)

@jakob do you have more info on this? I can't think of any fix for `LIKE` we made in 2.1 (CC @knz)

**Comment by knz** [comment] 2018-10-31 23:14
Changes to LIKE were made when we introduced support for ESCAPE. I don't remember the details though.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jakob** [comment] 2018-11-05 09:34
@RaduBerinde 
Here's a test query:
```sql
SELECT '\' LIKE '%\\', '\' LIKE '\\%', '\' LIKE '%\\%';
```

CRDB 2.0 returns: `TRUE, TRUE, FALSE`

CRDB 2.1 returns: `TRUE, TRUE, TRUE`

A similar query is executed as part of the Postico Table Filter test suite, so those tests always failed on CockroachDB. I'm happy that we have one less failing test case now :)

**Comment by jakob** [comment] 2018-11-07 14:22
Postico 1.4.3 is now released, and our regression tests run successfully against CockroachDB 2.0 and 2.1.

**Closed by jakob** 2018-11-07 14:22 UTC
