### ISSUE TITLE
Autocomplete crashing 100% of the time all of a sudden

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#774] opened 2021-06-12 15:08 UTC
Postico 2.0 beta 8259 here, did anything change recently? iCloud Library. Any time I use autocomplete, manual or automatic, it crashes kaboom. Attaching a crash log.

Very weird, very consistent, every time. Had to disable auto complete.
[crashreport.txt](https://github.com/jakob/Postico/files/6642421/crashreport.txt)

**Comment by martinjankoehler** [comment] 2021-06-14 10:22
Thanks for reporting this crash @wellsoliver,
we seem to have a regression with the latest function argument default quoting fixes.

We're trying to reproduce the problem.
Please let us know
- Which server version are you using?
- Any fancy argument defaults in your functions?

**Comment by wellsoliver** [comment] 2021-06-14 17:06
The servers are postgres 13.2 and 13.3. No fancy arguments at all, straight password connection, no SSH tunnels, no wild stuff.

**Comment by gdoe** [comment] 2021-06-14 17:08
I'm seeing the same issue, I just upgraded to Postico version 2.0beta (8263) and it still happens.

**Comment by martinjankoehler** [comment] 2021-06-14 20:03
@wellsoliver , @gdoe we've fixed this issue 
(_Autocomplete crashing 100% of the time all of a sudden_).

Available via the built-in autoupdater or via manual download here:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8269.dmg

Please let us know if the issue is now also fixed on your side.

Best regards and thanks again for reporting,
Martin

**Comment by wellsoliver** [comment] 2021-06-14 20:23
Hey! First few tests are definitely positive. Will post back if anything goes south. Thank you guys, it's an awesome little piece of software.

**Comment by gdoe** [comment] 2021-06-14 20:34
Good on my end so far too, thanks!

**Comment by martinjankoehler** [comment] 2021-06-14 21:06
Awesome, thanks for testing!
Closing this thread for now, please re-open or add a new issue in case something should come up.

**Closed by martinjankoehler** 2021-06-14 21:06 UTC
Labels: bug

**Comment by gareth** [comment] 2021-07-30 08:54
I have the same issue in Postico 1.5.19 (8260) on MacOS Big Sur 11.4 (20F71)

Can the fix you made be ported back to 1.5 or is the only option to upgrade to the 2.0 beta?

**Comment by jakob** [comment] 2021-07-30 11:11
@gareth There's an iCloud bug that causes Webkit to hang when loading, which causes Postico to hang when showing autocomplete. It affects both Postico 1 and 2, and to my knowledge there's nothing we can do to fix it, apart from rewriting the autocomplete code not to use Webkit. Could this be what's happening? Customers have reported that restarting their Mac fixes the iCloud issue.

**Comment by gareth** [comment] 2021-07-30 14:21
Thanks @jakob, restarting my Mac did resolve the issue and the autocomplete is now responsive. I guess the problem wasn't related to this Github issue, so sorry for the unnecessary bump!
