### ISSUE TITLE
"get row count" button in status bar when "retrieve row count" option is off

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#442] opened 2017-10-09 14:59 UTC
I have the "retrieve exact row count" option off since I have a few fairly big tables. 
But *sometimes* I need to know the row count and there is no convenient option for getting this information. Going to the SQL pane takes a relatively long time, but more importantly the pane is probably full of other queries and writing a on-off query somewhere into a 2k line sql script isn't the best.

Maybe (when the "retrieve exact row count" option is off) there could be a button in the status bar where the row count would be: `1 - 1000 of [get row count]`. There it would be discoverable and would not clunk up the UI too much.

What do you think?

**Comment by jakob** [comment] 2017-10-09 15:20
I think it is a good idea, which is why it is already on my issue tracker :)

I'm closing this issue since it is a duplicate of #423.

Thanks!

**Closed by jakob** 2017-10-09 15:20 UTC
Labels: duplicate

**Comment by qwesda** [comment] 2017-10-09 17:07
dammit, that issue slipped by me. 

great!
