### ISSUE TITLE
Crash, Version 1.0.2 (1282)

### ISSUE THREAD

**Issue by luckydonald** [jakob/Postico#167] opened 2016-01-23 22:04 UTC
Probably related to the Settings Dialog. I turned off Magic Mouse and Trackpad Gestures.
Version 1.0.2 (1282). Mac OS 10.9.5
```
2016-01-23 20:33:06.029 Postico[5874:507] Invalid color System, labelColor (warning given only once)
2016-01-23 21:10:15.400 Postico[5874:507] Layout still needs update after calling -[NSScrollView layout].  NSScrollView or one of its superclasses may have overridden -layout without calling super. Or, something may have dirtied layout in the middle of updating it.  Both are programming errors in Cocoa Autolayout.  The former is pretty likely to arise if some pre-Cocoa Autolayout class had a method called layout, but it should be fixed.
2016-01-23 21:16:58.656 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f9772c174d0 {conflictList=(
    "NSMergeConflict (0x7f977522c7c0) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new database row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 21:17:55.240 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f977522f890 {conflictList=(
    "NSMergeConflict (0x7f9772c13d40) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old object snapshot = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 21:18:09.182 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f9772cb6120 {conflictList=(
    "NSMergeConflict (0x7f9772cb7550) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old object snapshot = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 21:18:33.274 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f9772c86bc0 {conflictList=(
    "NSMergeConflict (0x7f9772c202e0) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old object snapshot = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 21:20:07.584 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f9772c2cae0 {conflictList=(
    "NSMergeConflict (0x7f9772c105c0) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old object snapshot = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 21:21:50.704 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f9772e374a0 {conflictList=(
    "NSMergeConflict (0x7f9772e7f220) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old object snapshot = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 22:15:04.393 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f9775004570 {conflictList=(
    "NSMergeConflict (0x7f9772d64090) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old object snapshot = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 22:15:06.828 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f9772f8cdb0 {conflictList=(
    "NSMergeConflict (0x7f9772f67170) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old object snapshot = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 22:17:15.987 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f9775220450 {conflictList=(
    "NSMergeConflict (0x7f9775235a50) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old object snapshot = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 22:17:22.765 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f9775284230 {conflictList=(
    "NSMergeConflict (0x7f977520b180) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old object snapshot = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 22:17:22.766 Postico[5874:507] Failed to create database object: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." UserInfo=0x7f9775128040 {conflictList=(
    "NSMergeConflict (0x7f97751adb70) for NSManagedObject (0x7f9772c9aa20) with objectID '0x40000b <x-coredata://A3A825A7-13BC-4728-8892-67F56D9023BB/PGEFavorite/p1>' with oldVersion = 1106 and newVersion = 1140 and old object snapshot = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n} and new cached row = {\n    colorIndex = 0;\n    database = \"<null>\";\n    host = \"<null>\";\n    nickname = localhost;\n    order = 1;\n    port = \"<null>\";\n    showAllDatabases = \"<null>\";\n    sshEnabled = \"<null>\";\n    sshHost = \"<null>\";\n    sshPort = \"<null>\";\n    sshPrivateKeyBookmark = \"<null>\";\n    sshUser = \"<null>\";\n    user = \"<null>\";\n}"
)}
2016-01-23 22:37:00.719 Postico[5874:507] Deallocated <PGETableMetadata: 0x7f977540acc0> before column query was done.
objc[5874]: Method cache corrupted. This may be a message to an invalid object, or a memory error somewhere else.
objc[5874]: receiver 0x7f9772e71ac0, SEL 0x7fff90efa010, isa 0x7f97753938f0, cache 0x7f9775393900, buckets 0x7f97753af420, mask 0x1, occupied 0x0, wrap bucket 0x7f97753af420
objc[5874]: receiver 256 bytes, buckets 224 bytes
objc[5874]: selector 'performSelector:withObject:'
Segmentation fault: 11
```

**Comment by luckydonald** [comment] 2016-01-23 22:05
Because (what I assume) storing of setting failed, I lost the changes in my SQL query editor :cry:

**Comment by jakob** [comment] 2016-02-03 17:12
The problem is probably that NSPageController (which is responsible for the "history stack" gestures) doesn't properly clean up connections to its view after being released... I've tried to address this in build 1306:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1306.zip

Could you let me know if the problem persists with this build?

**Comment by luckydonald** [comment] 2016-02-03 17:52
Side note, unrelated: Sometimes I accidentially initiate the page history slide gesture, which sometimes hangs halfway. This causes the whole app to deny all clicks.
Only the menubar is clickable. I cant even click the red bulb in the titlebar to close the window.

**Comment by jakob** [comment] 2016-02-05 09:30
@luckydonald I'm afraid that latter problem is a bug in OS X; I remember seeing it too, and I think it disappeared with some OS X update. Probably the best way around this is to disable Gestures on OS X 10.9

**Comment by jakob** [comment] 2016-02-09 16:21
I'm closing this issue for now; if you see the problem occurring again with the latest build, please reopen it.

**Closed by jakob** 2016-02-09 16:21 UTC

**Comment by jakob** [comment] 2016-02-10 20:49
It seems the problem did not go away; I just received another crash report from a customer via email.

It's likely that the reason for this crash is a bug in NSPageController, since it only occurs on OS X 10.9.

I've now added a workaround that tries to circumvent the bug by showing a dialog that tells the user to close the window to make changes effective. It's not an elegant solution, but it's nicer than crashing!

**Comment by jakob** [comment] 2016-02-10 20:49
And here's the build for testing:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1326.zip
