### ISSUE TITLE
1.4.2 does not accept my database password

### ISSUE THREAD

**Issue by fodor99** [jakob/Postico#575] opened 2018-07-19 05:56 UTC
## What did you do?

I input my password, but even copy paste cause auth error.
Password is: (RYDxn<Lh=j|+H

## What did you expect to happen?

I expect to connect to the database 

## What actually happened?

I got error message instead of connect:

FATAL:  password authentication failed for user ....

## What software versions are you using?

Postico version:  
1.4.2

macOS version:  
10.13.6

PostgreSQL version:  
PostgreSQL 9.5.4 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit

If I change my password for example to: 12345
Everything works fine.
I think, some of the characters handled in some different way.....

**Comment by jakob** [comment] 2018-07-19 12:40
There is no code that does any special handling of passwords in Postico -- the password is sent directly to libpq. I just tested this password, and it works correctly on my machine.

How did you set the password? Did you use the SQL command `alter user USERNAME password '(RYDxn<Lh=j|+H';`, or did you use a 3rd party tool?

It's also possible that there were some weird whitespaces or invisible characters in the password (common issue when copying things from a website).

Does logging into the server with psql work with the weird password?

**Comment by jakob** [comment] 2018-07-23 12:18
I'm closing this since I can't reproduce it. Feel free to re-open the issue if you still encounter it, or if you have additional information on how to reproduce it.

**Closed by jakob** 2018-07-23 12:18 UTC
