### ISSUE TITLE
Unable to 

### ISSUE THREAD

**Issue by droptablestar** [jakob/Postico#822] opened 2022-07-18 17:59 UTC
## What did you do?

- I deleted a password from a saved favorite configuration in Postico that I had previously stored in my Keychain and unchecked "Save in Keychain".
- Then I pressed Done.

## What did you expect to happen?

- I expected that password would be removed from the configuration.

## What actually happened?

- When I opened the configuration again the password is still saved.

## What software versions are you using?

Postico version:  
1.5.19 (8260)

macOS version:  
12.2.1

PostgreSQL version:  
PostgreSQL 13.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit

![image](https://user-images.githubusercontent.com/1942136/179573301-134909c7-68e9-4901-83a1-f21740b2fee5.png)

![image](https://user-images.githubusercontent.com/1942136/179573338-dbd6733c-3c0e-4984-bf91-98970b2d1241.png)

#### Click Edit
![image](https://user-images.githubusercontent.com/1942136/179573426-4b431572-80fd-4a04-a1ec-681eef248dd4.png)

I did change the Host so my actual host wasn't in the screenshot and that updated.

**Comment by jakob** [comment] 2023-07-11 11:58
Sorry for not getting back to you sooner.

This could be caused by multiple favorites with the same host. I've rewritten the keychain code in Postico 2 so this should not happen any more.

In any case, you can open Keychain Access, and manually remove the password (search for "postgres" or "Postico").

I'm closing this issue, feel free to reopen if the problem still occurs.

**Closed by jakob** 2023-07-11 11:58 UTC
