### ISSUE TITLE
Entire app freezes when you swipe back on trackpad

### ISSUE THREAD

**Issue by mwilliammyers** [jakob/Postico#403] opened 2017-07-24 06:08 UTC
Love the app. Nice work.

I am running: 10.13 Beta (17A306f) so I don't expect this to work but just thought I would let you know.

When I swipe to go back a view on the trackpad and there aren't any previous items to go back to the entire app freezes (this happens a lot on accident when I scroll left/right to view more columns in a result set). I cannot select or click on anything in the app. I can bring up windows from the top menu bar (eg settings) but I cannot interact with anything at all (nothing happens when I toggle check boxes, cannot select tables from the side menu etc.

**Comment by jakob** [comment] 2017-07-24 07:08
This is a duplicate of #397. It’s a bug in the High Sierra Beta. There’s nothing I can do to fix it except disable mouse gestures. (You can disable gestures in Postico preferences)

I’ve reported this to Apple, but I’ve not gotten a response yet.

You can help by also reporting this problem to Apple. If enough people complain, they might notice that they broke NSPageController, and fix it.

Unfortunately, experience shows that Apple doesn’t always fix reported issues before the final release – and I’m not sure if this API is important enough for Apple, since it’s not very popular and I don’t think they use it themselves...

**Closed** 2017-07-24 07:17 UTC

**Comment by jakob** [comment] 2017-07-26 11:23
I think this is fixed in High Sierra Beta 3. Could you update to the latest version and let me know if it works for you too?

**Comment by mwilliammyers** [comment] 2017-08-04 15:52
Updated to 10.13 Beta (17A315i) and it works great. Thanks!
