### ISSUE TITLE
Foreign key window closes when adding new foreign key

### ISSUE THREAD

**Issue by fsonntag** [jakob/Postico#531] opened 2018-05-02 10:28 UTC
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## What did you do?

- In the structure view of a table, under constraints of a column name:
- I click on the + to add a new constraint
- Then I click on foreign key

## What did you expect to happen?

- I expect to see the foreign key configuration window, staying

## What actually happened?

- The foreign key configuration window shortly appears and then disappears again

## What software versions are you using?

Postico version:  1.3.4

macOS version:  10.13.4

PostgreSQL version:  PostgreSQL 10.3 on x86_64-apple-darwin17.3.0, compiled by Apple LLVM version 9.0.0 (clang-900.0.39.2), 64-bit

**Comment by jakob** [comment] 2018-05-02 10:29
This is a dupe of #528 which we have just released a fix for (Postico 1.3.5). If you have the Mac App Store version, an update should be available in a few hours.

**Comment by fsonntag** [comment] 2018-05-02 10:31
Oh, I'm sorry. I have only looked through the open issues, not the closed ones... I will update now!

**Comment by jakob** [comment] 2018-05-02 10:35
Don't worry. I prefer to get duplicate reports to getting no reports! So thanks for taking the time to report this, even if it was reported before.

**Comment by fsonntag** [comment] 2018-05-02 10:36
Also works like a charm with 1.3.5 👍

**Closed** 2018-06-11 11:30 UTC
