### ISSUE TITLE
UI Suddenly Freezes Up, with no recovery

### ISSUE THREAD

**Issue by miksago** [jakob/Postico#124] opened 2015-11-15 03:15 UTC
This happens when changing views and when scrolling. Postico was working fine for several days, and this issue has suddenly appeared.

Even trying to close windows opened by Postico doesn't work (however, oddly, I can open more windows, which are also frozen, and which I subsequently can't close).

Reinstalling from scratch (nuking everything via CleanMyMac 2) did not resolve the issue.

In Console.app, I get the following messages:

```
15/11/2015 4:11:56.541 am Postico[2855]: CoreText CopyFontsForRequest received mig IPC error (FFFFFFFFFFFFFECC) from font server
15/11/2015 4:11:56.541 am Postico[2855]: CoreText CopyFontsForRequest received mig IPC error (FFFFFFFFFFFFFECC) from font server
```

System Version:	OS X 10.9.5 (13F1112)
Postico Version:	1.0 (1234)

**Comment by miksago** [comment] 2015-11-15 03:20
Also get the following in the logs, but these seem unrelated:

```
15/11/2015 4:11:15.988 am Postico[2855]: nil is not a valid object ID
15/11/2015 4:11:16.060 am Postico[2855]: Invalid color System, secondaryLabelColor (warning given only once)
```

**Comment by jakob** [comment] 2015-11-16 14:03
This is odd. If I understand correctly, the database windows stop responding, but the favorites window keeps working?

The log messages might be related to fonts and styles not available in OS X 10.9; however everything worked when I tested it. Does a specific view cause your issues (eg. content view, structure view, sidebar, etc.)?

Also, just to make sure this isn't caused by a bug in the window server, did you already try restarting your Mac?

**Comment by miksago** [comment] 2015-11-17 12:07
Nope, all freeze � I can still open new windows from the universal menu bar though.

I haven't restarted my mac in a little while � I am meaning to do it, but busy developer life :(

**Comment by jakob** [comment] 2015-11-18 15:41
OK. In that case try restarting your Mac, and see if the problem goes away.

If the problem persists, it would be helpful if you could generate a spindump (while Postico is frozen). You can generate a spindump like this:
```bash
sudo spindump Postico -file ~/Desktop
```
Compress the file and email it to me: jakob@eggerapps.at

**Comment by miksago** [comment] 2015-11-18 17:13
hmm, I'm unable to reproduce now; Will follow your instructions if it happens again.

**Comment by jakob** [comment] 2015-11-23 08:49
OK. I'll assume that this was a one time glitch with the window server, and close this issue for now. Please reopen it if you run into it again!

**Closed by jakob** 2015-11-23 08:49 UTC
