### ISSUE TITLE
Feature request: granular notification settings

### ISSUE THREAD

**Issue by smbkr** [jakob/Postico#342] opened 2017-03-10 14:33 UTC
Hi there @jakob 

I'm enjoying Postico, however would like to suggest adding granular control over the notifications. I'm not interested any notifications for completed queries, however would like to retain notifications for things like disconnections etc.

Cheers.

**Comment by jakob** [comment] 2017-03-21 14:31
@smbkr Postico should only notify you when a query completes while the app is in the background. It can happen that unnecessary notifications are displayed when multiple versions of the app are running.

**Comment by linearray** [comment] 2017-12-13 19:01
This is not the case. Every query causes a notification to be sent (postico 1.2.3, macOS 10.13.2).

**Comment by jakob** [comment] 2017-12-13 20:20
@linearray
Normally macOS should ignore notifications when Postico is in the foreground.

Did you check in activity monitor if you have a second copy of Postico running (eg. an older version?)

Does the problem persist after restarting your Mac?

**Comment by linearray** [comment] 2017-12-13 20:23
It is ignored insofar as the notification is not shown, but it is created and listed in the notification center. Maybe that is the intended behaviour, I just expected no notification at all when Postico is in the foreground.

**Comment by jakob** [comment] 2017-12-13 21:06
Hm. Having these notifications show up in notification center at all doesn‘t really make much sense...

I‘ll have to check the docs if there is some kind of ephemeral notification mode we could use.

**Comment by jakob** [comment] 2018-04-04 15:06
Fixed in Postico 1.3.3

**Closed by jakob** 2018-04-04 15:06 UTC
