### ISSUE TITLE
Copy special JSON: use json instead of string for JSONB field type

### ISSUE THREAD

**Issue by Aymericr** [jakob/Postico#489] opened 2018-01-25 19:17 UTC
Can you use JSON format instead of String for JSONB field type when copying rows?

**Comment by jakob** [comment] 2018-02-16 10:05
I assume this is a duplicate of #448, or did I misunderstand?

**Comment by martinjankoehler** [comment] 2021-04-28 11:24
Hey @Aymericr,

thanks for reporting this issue.

We have fixed the JSON representation for JSONB field types, the value now becomes proper JSON instead of a string.

The next Postico 1.5.18 release will contain this fix, in the meantime this preview build is available for testing:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8035.zip

The latest Postico 2 Beta update (8038) also contains this fix and is available using the built-in updater,
or as a direct download: https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8038.dmg

Closing this issue now, please feel free to re-open or add a new issue should any other problems occur.

Best regards,
Martin

P.S.: 
- we've also added Copy Special support for JSON lines format
- Postico 2 full table export feature now also supports JSON (table sidebar context menu `Export <name>…` or main menu `File > Export <name>…`)

**Closed by martinjankoehler** 2021-04-28 11:24 UTC

**Comment by martinjankoehler** [comment] 2021-06-07 12:27
Postico 1.5.18 was released today [(download)](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.18.zip)
