### ISSUE TITLE
CSV Export fails when field contains quote (") characters

### ISSUE THREAD

**Issue by waveforms** [jakob/Postico#773] opened 2021-06-08 19:31 UTC
Thanks for Postico! I love it.

This is a problem I discovered since the recent Postico update.

## What did you do?

- I clicked on "Export a table" as csv. Format:International, Encoding: uff 8
- Then I tried to import the csv into a duplicate table and Postico generated the beach ball.
- NOTE: the table had a json_blob field and the json blob had a different number of fields (per row)
- also tried to read the generated csv with xsv https://github.com/BurntSushi/xsv and it was unable to parse.
- workaround, export csv via dbeaver. Can then be imported by Postico.

## What did you expect to happen?

- I expected to see it import the csv data back into the database in the new table. This is what successfully happened in versions before 1.5.18

## What actually happened?

- The app crashed.

## What software versions are you using?

Postico version:  1.5.18
(select "About Postico" from the Postico menu)

macOS version:  Big Sur
(selecting "About this Mac" from the Apple menu)

PostgreSQL version:  PostgreSQL 13.2 on x86_64-apple-darwin20.3.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
(execute the command "SELECT VERSION();" to find out)

**Comment by jakob** [comment] 2021-06-09 06:46
Thanks for letting us know about this issue.

As far as I can tell there are two possible issues:

1) Postico 1.5.18 generates different CSV than Postico 1.5.17 when exporting
  - could you try downloading Postico 1.5.17 and check how the generated CSV differs from the CSV generated by 1.5.18? You can check for differences eg. with the `diff` command line tool.

2) Postico 1.5.18 hangs (Beachball) when trying to import CSV.
  - could you check if Postico 1.5.17 also hangs for the same CSV file?
  - could you try to create a sample of Postico when it is hanging? (See "When Postico Hangs" on [this page](https://eggerapps.at/postico/docs/v1.5.18/reporting-bugs.html))

Of course the easiest way for us to reproduce this issue would be if you could send us a (partial) dump of the problematic table, but that's only an option if the table does not contain any confidential data.

**Comment by jthele** [comment] 2021-06-10 04:53
This may be obvious, but this issue is not limited to just fields containing JSON blobs.  Any field containing a double quote is not being properly escaped when exported to CSV.

I would request the issue title be amended to capture the greater scope of the problem.

**Comment by jthele** [comment] 2021-06-10 04:55
Reproduction instructions:

**Comment by jakob** [comment] 2021-06-10 10:26
Thanks for the updates! We've been able to reproduce the issue now. It seems we made an error when we refactored the CSV export code.

> Can 1.5.17 and 1.5.18 be installed on the same system?
Yes, but you may see some odd behaviour if you open both versions of the app at the same time.

**Comment by jakob** [comment] 2021-06-10 12:52
We've fixed the CSV quoting issue!

I'd appreciate if you could download this build and verify that it fixes the issue:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8245.zip

**Comment by jakob** [comment] 2021-06-10 12:58
@waveforms You originally said:
> Then I tried to import the csv into a duplicate table and Postico generated the beach ball

While we fixed the problem with CSV import, this looks like a separate issue. Postico should not hang on invalid CSV files, it should show an error message. Can you share any more info about the type of file that caused the hang in Postico?

**Comment by jthele** [comment] 2021-06-10 14:38
> I'd appreciate if you could download this build and verify that it fixes the issue:

Downloaded and confirmed fix is exporting double quotes as expected.

**Comment by waveforms** [comment] 2021-06-10 19:04
Thanks for the quick response! I will test when I get some time. Since the beachball is a separate issue perhaps you should close this.
> Can you share any more info about the type of file that caused the hang in Postico
It was a larger version of the bad csv fragment I sent. Unfortunately the data is confidential so it would take a long time to scrub. As rough guide, if you were to convert the csv to standard pdf it would be about 30 pages.

**Comment by martinjankoehler** [comment] 2021-06-14 09:38
Thanks folks!

@waveforms: OK, I'll close this issue. 
Please open a separate one with details on the hang when you're ready.

Best regards,
Martin

**Closed by martinjankoehler** 2021-06-14 09:38 UTC
Labels: bug
