### ISSUE TITLE
v1.3 with Redshift crashes when auto-completion shows

### ISSUE THREAD

**Issue by KOBA789** [jakob/Postico#470] opened 2017-12-14 15:25 UTC
Procedure to reproduce:

1. Connect to a Redshift.
2. Open "SQL Query" view.
3. Type some SQL: `select * from some_schema`.
4. Finally, type `.`.
5. A popup appears and then Postico crashes immediately.

Crash Report: https://gist.github.com/KOBA789/229b394adbbd7cde26a95fa0dce31666

**Comment by jakob** [comment] 2017-12-14 18:52
Thanks for the crash report! We couldn‘t reproduce the issue you describe (it works on our Redshift test cluster), but we tried to make Postico more resilient wrt. NULL responses from the server.

Can you check if build 2144 works for your database?

https://eggerapps.at/postico/builds/

**Comment by KOBA789** [comment] 2017-12-14 19:19
Thanks for your quick response!

I tried build 2144 and it never crashes!

My broken version which was downloaded via the notification is 2142.
Are there any differences?

**Comment by jakob** [comment] 2017-12-14 20:34
Yes, build 2144 has additional checks for NULL values. (Martin added them after looking at your crash report)

**Comment by teej-minted** [comment] 2017-12-14 20:47
After doing loads more testing (after the last email I sent you @jakob), I believe that it's some kind of race condition type of issue. I am still having crashes on 2144. If I go very slowly I don't crash, if I go normal speed I crash.

**Comment by jakob** [comment] 2017-12-14 22:05
@teej-minted Thanks for trying the new build. I think you found an unrelated crash. I'll investigate tomorrow morning.

**Comment by jakob** [comment] 2017-12-15 16:19
Short update on the crash reports: We‘ve analysed them, and discovered that the crash is caused by a memory error. (We think that the items in the suggestion list are released too early)

We’ve not yet found the root cause of the issue, and we also haven‘t been able to reproduce the crash yet.

I think that so far we‘ve had reports of the problem only on Redshift, but oddly everything works on our Redshift test cluster.

I‘ll keep investigating the problem. In the mean time, you can use version 1.2.4 until the issue is fixed: https://eggerapps.at/postico/legacy.html

**Comment by jakob** [comment] 2017-12-18 14:36
We've finally been able to reproduce the second crash. It has nothing to do with Redshift, but it happens only on macOS 10.11. It can be triggered for example by typing "pg_", then pressing the tab key three times, then pressing return.

We've addressed the underlying problem (we forgot to call -reloadData in some cases).

@teej-minted Could you verify that build 2151 works for you now?

**Comment by jakob** [comment] 2017-12-19 10:08
We've released Postico 1.3.1 which should fix both issues reported here. I'm closing this issue. If the crash still occurs, you can reopen this issue, or create a new one.

Thanks a lot for your feedback!

**Closed by jakob** 2017-12-19 10:08 UTC

**Comment by teej-minted** [comment] 2017-12-19 18:08
Just tested v 1.3.1 (2153) and it works great for me with no crashes!
