### ISSUE TITLE
add find-and-replace in SQL Query view

### ISSUE THREAD

**Issue by jmcbroom** [jakob/Postico#165] opened 2016-01-21 18:18 UTC
would be nice to have find-and-replace for the text in the query editor; both for the whole editor and a selection. thanks. Postico is great so far.

**Comment by teneruffian** [comment] 2016-01-22 13:16
I was just thinking the same thing.  So that's a "please" from me, also.
And a thank you for the app.

**Comment by nksocast** [comment] 2016-02-02 00:06
+1, please add this feature.

**Comment by swrobel** [comment] 2016-02-04 17:15
Duplicate of #53

**Comment by jakob** [comment] 2016-04-01 15:06
I've now added find & replace in the query editor

Download latest nightly build here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1402.zip

**Closed** 2016-04-12 13:32 UTC
Labels: fixed
