### ISSUE TITLE
parenthetical highlighting would be a useful added feature in later releases

### ISSUE THREAD

**Issue by chaz9456** [jakob/Postico#199] opened 2016-03-29 13:38 UTC
In the sql editor, it's easy to lose track of what parentheses are "matching pairs". It's really helpful when the cursor is on a parenthesis to be able to clearly see it's matching pair highlighted. Furthermore, it's nice when "unclosed" parentheses are highlighted for the user to know immediately that there's a parentheses problem. Pgadmin III has these features. 
As far as I can tell this feature currently doesn't exist, but I think it would be a really powerful feature to add. Did me wonders in the pgadmin days.

**Comment by mrkcohen** [comment] 2016-05-06 18:43
+1

**Comment by jakob** [comment] 2016-10-11 14:19
(duplicate of #151)

**Comment by jakob** [comment] 2020-04-03 14:36
Postico 2 highlights matching parentheses and mismatched parentheses.

See https://eggerapps.at/postico2/ and #689 for details.

**Closed by jakob** 2020-04-03 14:36 UTC
