### ISSUE TITLE
Feature Request: Read-only flag

### ISSUE THREAD

**Issue by kevart** [jakob/Postico#253] opened 2016-08-12 05:16 UTC
Helps to not accidentally make changes to the production database.

**Comment by wellsoliver** [comment] 2016-08-23 04:59
can't this be solved w/ proper permissions?

**Comment by jakob** [comment] 2016-08-23 10:03
I agree with @wellsoliver that the safest way to handle this will be to create a user that doesn't have any write permissions.

However, the [SET TRANSACTION COMMAND](https://www.postgresql.org/docs/9.5/static/sql-set-transaction.html) in PostgreSQL allows making transactions read-only. By setting the [default_transaction_read_only ](https://www.postgresql.org/docs/9.5/static/runtime-config-client.html#GUC-DEFAULT-TRANSACTION-READ-ONLY) parameter, one could make the connection read-only until you execute SET TRANSACTION READ WRITE.

Unfortunately Postico has no way to set default parameters for connections. I'm planning to add support for connection parameters at some point, since they are often also useful for other things (eg. search_path), but I can't make any promises concerning timeline.

**Comment by jakob** [comment] 2016-08-26 10:56
I just realised this is a duplicate of #207

**Closed by jakob** 2016-08-26 10:56 UTC
Labels: maybe-later
