### ISSUE TITLE
Cursor becomes occluded by gutter when digit added to line numbers.

### ISSUE THREAD

**Issue by lgomez** [jakob/Postico#567] opened 2018-06-29 00:44 UTC
## What did you do?

- Normal usage of SQL Query view.
- Added enough lines to go from single-digit number of lines to double-digit number of lines.

## What did you expect to happen?

- I expected to be able to see my cursor even when at column 1.

## What actually happened?

- The gutter becomes wider to make space for double-digit line numbers but fails to push editor to the right therefore cursor is occluded by gutter and one looses track of it.

## What software versions are you using?

* Postico version: 1.4.2 (2845)
* macOS version: 10.14 Beta (18A314k)
* PostgreSQL version:  PostgreSQL 9.6.6 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

## > 1000 words
![postico-line-number-cursor-visibility-bug](https://user-images.githubusercontent.com/20891/42067342-9a970b40-7afa-11e8-99ae-2e2aebbe4684.gif)

**Comment by lgomez** [comment] 2018-06-29 00:46
Note that I noticed this after upgrading to the most recent Beta version of OSX but also after upgrading to the latest version of Postico. Not sure if it happened with the previous release of Postico on OSX's beta version.

**Comment by jakob** [comment] 2018-06-29 08:09
Thanks for reporting this issue!

I think this is a duplicate of #553

We haven't had time to fix all the Mojave bugs yet. Apple broke a lot of user interface elements in this update, and I'm not sure yet if this is a bug in NSTextView, or if an intentional change in NSTextView requires us to change our code.

**Closed by jakob** 2018-06-29 08:09 UTC
