### ISSUE TITLE
Editing constraints is not possible

### ISSUE THREAD

**Issue by gajus** [jakob/Postico#388] opened 2017-05-30 16:11 UTC
Unless I am not understanding the UI, it appears that it is impossible to edit a constraint:

<img width="486" alt="screen shot 2017-05-30 at 17 10 32" src="https://cloud.githubusercontent.com/assets/973543/26593120/f21951b0-455a-11e7-9036-4464a50e3992.png">

An IDE should be able to achieve that by simply recreating the constraint. (Which what the user needs to do now anyway.)

Is there a reason this is not possible?

**Comment by jakob** [comment] 2017-05-30 21:13
(This is a duplicate of #264)

The reason that it is not possible is that I haven't gotten around to implement it yet. I have this scheduled for the next milestone, but I'm not totally sure if I can make it.

**Closed by jakob** 2017-05-30 21:13 UTC
