### ISSUE TITLE
Cannot paste into SQL window

### ISSUE THREAD

**Issue by MrHen** [jakob/Postico#244] opened 2016-07-26 18:08 UTC
I am unable to paste into the SQL window/pane. I have tried Command-V, Ctrl-V, using the menu and using the context menu.

I am running Mac OS X 10.11.4 (15E65) and Postico 1.0.8 (1442).

I downloaded the application from this link: https://eggerapps.at/postico/

---

Specific repro steps:
- Open Postico
- Start new connection to a database
- Double-click on the SQL Query option
- Inside of the SQL Query pane, try to paste

**Comment by jakob** [comment] 2016-07-27 15:23
Pasting works fine for me.

1. The keyboard shortcut for pasting is Cmd-V, like all other Mac apps.
2. Does the window look similar to the screen shot below? If not, can you send a screenshot?
3. Did you make sure the text area is active (blinking insertion mark)?
4. Could you double check if there is actually something in your clipboard?
5. Postico can only paste text. Try copying something from Text Edit. Maybe the app you are copying from uses a non-standard format.


<img width="801" alt="screen shot 2016-07-27 at 17 16 28" src="https://cloud.githubusercontent.com/assets/198305/17180915/54b3d612-541e-11e6-9a32-8ab72edf282c.png">

**Comment by MrHen** [comment] 2016-07-28 14:48
Yes, sorry, I meant Cmd-V. I updated the issue.

I attached a screenshot of the window I see. It looks like yours.

* I cannot from Text Edit either
* If I copy _from_ Postico, I still cannot paste into Postico
* The only other person I know who uses Postico does _not_ have this issue. It has never pasted correctly for me.

<img width="809" alt="screen shot 2016-07-28 at 9 46 52 am" src="https://cloud.githubusercontent.com/assets/74260/17216904/22f6ef8a-54a8-11e6-92ea-e72da3ee6313.png">

**Comment by jakob** [comment] 2016-07-29 09:20
OK, I'm stumped. Could you open Console.app and see if any error message are written when you try to paste?

Do any other apps on your system have the same issue?

Could you try disabling white-space sanitation? Maybe that causes the issue? Type the following in Terminal, then quit & restart Postico:
```bash
defaults write at.eggerapps.Postico SanitizeWhitespace 0
```
(if that wasn't the cause, execute the command again, replacing 0 with 1 to reenable whitespace sanitation)

**Comment by MrHen** [comment] 2016-08-01 14:26
Console has this output:

```
8/1/16 9:21:20.161 AM Postico[34939]: Can't allocate a new block for a pasteboard. Creation of a new Pasteboard will fail.
```

However, I also see that message when pasting into Chrome and the paste still works.

----

Disabling whitespace sanitation _did_ fix the problem! It also removed the Console symptom: pasting no longer causes the "Can't allocate a new block" error.

I will use this workaround for now; if you have anything else you want me to try, let me know.

**Comment by ghecho** [comment] 2016-08-28 18:53
I was having the exact same problem in version 1.0.9, The console showed the same message and the  "disabling white-space sanitation" command worked, now I can paste into the editor.

**Comment by macarthy** [comment] 2017-01-11 04:57
"disabling white-space sanitation" + 1

**Comment by indigoviolet** [comment] 2017-04-14 23:30
+1

**Comment by jakob** [comment] 2017-04-19 11:02
I've now fixed the whitespace sanitation feature in build 1640.

Postico now no longer tries to fix whitespace while pasting, but fixes whitespace automatically when sending the query to the server. Pasting should work again now.

If you've had problems pasting into the SQL Query before, could you try a recent build from here?
https://eggerapps.at/postico/builds/

**Closed** 2017-05-05 19:06 UTC

**Comment by zhulinpinyu** [comment] 2017-08-02 06:02
Great, Thanks for https://eggerapps.at/postico/builds/ 👍
