### ISSUE TITLE
DDL tab doesn't refresh table definition as schema changes

### ISSUE THREAD

**Issue by fxer** [jakob/Postico#556] opened 2018-06-11 23:03 UTC
The new DDL tab is fantastic! Already getting use out of it, think I ran into a prob with the table definition displayed not being updated as the schema changes

## What did you do?

1) Looked at DDL tab TABLE CREATE statement
1) Deleted an index
1) Refreshed table list, still saw deleted index on DDL tab (but not on Structure tab)

## What did you expect to happen?

INDEX would have been removed from the DDL TABLE CREATE tab statement

## What actually happened?

INDEX still displayed on DDL tab

## What software versions are you using?

Postico version:  1.4

macOS version:  10.13.5

PostgreSQL version:  9.6 (google cloud sql)

**Comment by jakob** [comment] 2018-06-12 08:43
Hmm, I can't reproduce this on my machine. I've tried several variations of your steps, but it always works as expected on my machine. The only way I managed to get stale data was by deleting the index manually without refreshing (eg. execute DROP INDEX in the SQL Terminal, and don't press cmd-R)

Did this happen only once, or is the bug reproducible every time? If you can reproduce it every time, can you describe the sequence of steps in more detail (eg. every mouse click / key press), or perhaps even email us a screen recording?

If you want to make a screen recording, you can record the screen with quicktime player, and email us the file to postico@eggerapps.at

**Comment by jakob** [comment] 2018-09-20 08:13
Hi! Since we haven't been able to reproduce this issue, and we received no followup, I'm closing this issue.

If you still experience the problem, or have any details that could help us understand, please feel free to reopen this issue any time!

**Closed by jakob** 2018-09-20 08:13 UTC
