### ISSUE TITLE
Connect via SSH crashing in 1.4

### ISSUE THREAD

**Issue by studouglas** [jakob/Postico#558] opened 2018-06-12 21:07 UTC
## What did you do?

Attempted to connect to a favourite that uses the "Connect via SSH" option. I frequently connect to this favourite, and haven't had any issues before today (when I updated to 1.4).

## What happened?

The app crashed immediately. Connecting to local databases works fine.

## What software versions are you using?

Postico version:  1.4 (2796)
macOS version:  10.13.5
PostgreSQL version:  PostgreSQL 9.6.9 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit

## SSH Configuration

![screen shot 2018-06-12 at 17 03 02](https://user-images.githubusercontent.com/8702605/41317380-05954dfc-6e63-11e8-9dc6-398c19641bd3.png)

**Comment by jakob** [comment] 2018-06-13 04:32
Hi!

Can you send us the crash report? You should be able to find it in `~/Library/Logs/Diagnostic Reports/`

Also, if possible, can you send us the output from `ssh -v SSH_USER@SSH_HOST -i ~/.ssh/id_rsa` (replacing SSH_USER and SSH_HOST with the SSH user and host from your favorite)?

You can reach me privately at jakob@eggerapps.at

**Comment by jakob** [comment] 2018-06-14 11:39
It looks like this is related to the key exchange method curve25519-sha256. (Previous versions of Postico didn't support it)

I haven't been able to reproduce the issue yet.

**Comment by studouglas** [comment] 2018-06-14 14:10
OK thanks for the update. If there's anything else I can help with let me know.

I reverted to Postico 1.3 for now and it's working fine.

**Comment by wilkens** [comment] 2018-06-14 18:59
I'm seeing the same problem on MacOS 10.13.5. Will send the crash report and diagnostic output by email. FWIW, I'm using username/password authentication, not key exchange (though that doesn't rule out something related to key exchange, of course).

**Comment by jakob** [comment] 2018-06-14 19:53
Hey everyone!

I haven't been able to reproduce the bug myself, but I think I found the underlying reason. (Thanks a lot for sending crash reports!).

It would be really awesome if you could try build 2839 (linked above), and see if it still crashes!

Thanks!

**Comment by wilkens** [comment] 2018-06-14 20:04
Thanks, Jakob. Yes,the new build (2839) works for me. No more crashes when connecting via SSH.

**Comment by studouglas** [comment] 2018-06-15 14:50
Hi Jakob, build 2839 works for me too! Thank you!

Just a heads up that build 2841 (Postico 1.4.1) does not work for me. It doesn't crash, but I get "Connecting to the SSH server failed. Unable to exchange encryption keys" when trying to connect.

Will stick with 2839 for now.

**Comment by wilkens** [comment] 2018-06-15 15:13
Thanks, Jakob. One more data point: 1.4.1 does work for me.

**Comment by wilkens** [comment] 2018-06-17 13:03
FWIW, 2844 is working fine for me. But 1.4.1 (2841) was already OK in my case, too.

**Comment by jakob** [comment] 2018-06-17 14:32
@wilkens Thanks for testing!

I've broken ed25519 host key verification in 1.4.1 by linking with a new version of OpenSSL. I think you have an ecdsa host key, so the problem wouldn't affect you.

SSH is starting to support a *lot* of crypto algorithms, so it's getting harder to test every configuration.

**Comment by jakob** [comment] 2018-06-18 09:49
Short update: I've now manually retested all possible host key / client key combinations, and it is looking good. (It's unfortunate that starting sshd requires root, otherwise I would have added this to the automatic test suite)

I released Postico 1.4.2. Hopefully this now fixes all SSH issues for everyone.

I'm closing this issue now; please reopen if you find any additional issues with SSH (or create a new issue if you are not sure it is related)

**Closed by jakob** 2018-06-18 09:49 UTC

**Comment by studouglas** [comment] 2018-06-18 13:37
1.4.2 works great for me, thanks!
