### ISSUE TITLE
New Postico 2 update now creating a new query on connect?

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#737] opened 2020-11-10 18:06 UTC
This seems to have just changed with the latest update (I am on 2.0b, 7343), but it now creates a new `SQL Query X` each time I re-open it, whereas before it just returned to the state. The creation of the new queries is kinda annoying and I can't seem to turn it off. Is there an option that changed? Preferences look the same to me.

I have `Server List` set for *New windows open with* and `Same View` set for *New tabs open with*

**Comment by jakob** [comment] 2020-11-10 20:12
Thanks for reporting this. I've been able to reproduce this, with a library stored in iCloud or on a slow drive (or a network drive).

We'll investigate this.

**Comment by jakob** [comment] 2020-11-10 21:02
OK, I think I found the bug. Postico called `startAccessingSecurityScopedResource()` on the wrong URL, so it failed to read the directory. Because of another bug in the error handling code it ignored the error and assumed the directory is empty. Then it decided to create a new query file, and that code path used the correct URL.

All the sandboxing tech in macOS is pretty impressive, but it makes it so hard to write working code :)

The following build should fix the bug:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7357.dmg

(This fix is not yet merged into the master branch, Martin will probably review it tomorrow)

**Comment by wellsoliver** [comment] 2020-11-11 00:32
Perfect, thanks!

**Closed** 2020-11-24 10:19 UTC
Labels: bug
