### ISSUE TITLE
Performance issues in large tables with NUMERIC columns

### ISSUE THREAD

**Issue by zingmane** [jakob/Postico#761] opened 2021-04-16 12:01 UTC
## What did you do?

I have a table with ~40.000 entries and ~80 columns 4 of them of type NUMERIC, no index or special stuff.
I do a:
```sql
select * FROM my_table; 
```

## What did you expect to happen?

- The result is complete in a few milliseconds

## What actually happened?

- The result is complete in ~5100 ms
- The same query in postico 1 takes ~500 ms

## What software versions are you using?

Postico version:  
`Version 2.0beta (7901)` vs `postico 1.5.16`

**Comment by jakob** [comment] 2021-04-16 14:31
Thanks for the report. This is probably caused by our recent changes to the handling of NUMERIC columns.

I can confirm that the following query takes roughly 5 seconds with the new code, and 200ms with the old code.
```sql
select n::numeric from generate_series(1,40000) as g(n);
```

**Comment by martinjankoehler** [comment] 2021-04-22 09:29
Hello @zingmane 

we've been working on this issue,
a fix is available via the latest automatic update,
or using this build: https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8031.dmg

Please let us know if the issue is also fixed on your side.

Best regards and thanks,
Martin

**Comment by jakob** [comment] 2021-05-05 14:24
I'm closing this issue since as far as I can tell it is fixed. Thanks again for reporting it!

**Closed by jakob** 2021-05-05 14:24 UTC
Labels: bug
