### ISSUE TITLE
Too much padding/whitespace in result grid

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#87] opened 2015-10-14 18:55 UTC
The result grid is too padded, or the columns are too wide in the results grid. I'm wondering if there is a way to set it so the columns are only as wide as their column names, or perhaps an option to auto adjust for the widest amount of data. I just see columns that are 3 or 5x wider than the column name and the data shown, not sure why...

**Comment by wellsoliver** [comment] 2015-10-14 19:20
![screen shot 2015-10-14 at 11 55 41 am](https://cloud.githubusercontent.com/assets/142900/10494936/fc03c906-726d-11e5-87cc-3292ff101aac.png)

**Comment by jakob** [comment] 2015-10-14 22:16
At the moment Postico has default column widths for different each data type. You can autosize a column by double clicking the separator. Postico will also remember when you changed column widths and you open the table again next time.

I agree that it might be useful to autosize columns based on their actual contents.

**Comment by wellsoliver** [comment] 2015-10-27 16:48
The double clicking to autosize thing works great-- wondering why the query grid result can't be sized in that manner by default?

**Comment by jakob** [comment] 2015-10-27 18:14
Autosizing can only be done after the data has finished loading, but the columns are already displayed as soon as the metadata is loaded. I wanted to avoid changing column sizes automatically after they have already been displayed since that would lead to the interface jerking around. Sudden changes in the UI that are not caused by user actions can lead to poor user experiences.

But I see now that the current behavior isn't very good either, so I will change this in the future.

**Comment by wellsoliver** [comment] 2015-10-29 16:28
cool, just a thought: maybe a button that's enabled after all data is fetched that auto-sizes all cells?

**Comment by wellsoliver** [comment] 2015-12-05 19:42
just +1ing myself here, it's really a drag on the workload to constantly resize the cells after pulling a query-- maybe a quick button or preference to autosize all columns after query complete or something?

**Comment by jakob** [comment] 2016-01-26 10:31
I've now implemented an algorithm that tries to intelligently resize table columns. Could you try the following build to see if it works as you expect?
https://eggerapps-downloads.s3.amazonaws.com/postico-1304.zip

**Comment by wellsoliver** [comment] 2016-01-26 19:06
!!! After a only a few hours using it this AM, it's a wonderful improvement. I haven't seen anything totally weird or exploded. It's a big improvement. Thank you!

**Comment by jakob** [comment] 2016-01-26 19:07
Good to hear! I ended up with quite an elaborate algorithm to size the columns; if you run into any odd cases let me know!

**Comment by jopotts** [comment] 2016-01-29 13:12
Tried 1304 and it's working well for me. There's a very slight extra delay on first viewing a table compared to the current (1292) build but hardly noticeable and worth it for the benefits.

Also I may as well cross-re-raise-reminder the issue of the rows being double height whilst I'm here: https://github.com/jakob/Postico/issues/26

You're doing an amazing job @jakob! Thanks!

**Comment by jopotts** [comment] 2016-03-02 12:07
Loving the recent enhancements. This issue is pretty much ready to close although I've discovered one very minor thing: [animated gif](http://f.cl.ly/items/2R0J21430j213o042K3T/Screen%20Recording%202016-03-02%20at%2012.00%20pm.gif)

I think it happens when the first column gets truncated to ellipses due to width restrictions (when first displaying the results), then when expanding the column it doesn't refresh for some reason. Possibly an OSX issue and out of your control.

**Comment by jakob** [comment] 2016-03-02 12:44
@jopotts thanks for reporting this -- this looks like a horrible bug, and completely my fault (there's an error in the caching logic). This build should fix it: https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1343.zip

**Comment by jopotts** [comment] 2016-03-03 11:03
I tried the new build and can't reproduce the issue. Thanks for the quick fix.

**Comment by jakob** [comment] 2016-03-04 10:36
fixed in 1.0.5

**Closed by jakob** 2016-03-04 10:36 UTC
Labels: enhancement, started
