### ISSUE TITLE
Feature request: specify pgFormatter options

### ISSUE THREAD

**Issue by bfelbo** [jakob/Postico#794] opened 2021-11-12 12:34 UTC
It's awesome you've added formatting (https://github.com/jakob/Postico/issues/155). We'd love to use it, but don't use the default values (see e.g. `--wrap-after` in https://github.com/darold/pgFormatter). Would it be possible to specify the pgFormatter options?

**Comment by martinjankoehler** [comment] 2021-11-12 13:47
@bfelbo Postico 2 now makes use of the settings in `~/.pg_format` (since build 8974),
available via the built-in autoupdater or manually at https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8975.dmg

Here's a template file to start:
https://github.com/darold/pgFormatter/blob/master/doc/pg_format.conf.sample

Dupe of https://github.com/jakob/Postico/issues/790

**Closed** 2021-11-12 14:08 UTC

**Comment by bfelbo** [comment] 2021-11-12 14:50
Amazing, thanks!
