### ISSUE TITLE
SSL error on Big Sur beta

### ISSUE THREAD

**Issue by dasdy** [jakob/Postico#728] opened 2020-09-23 13:49 UTC
## What did you do?
I am currently running macOS Big Sur (20A5374i). After installing the update, Postico and Postico 2 stopped connecting to remote databases (I have several GCP-hosted Postgres instances, and all of them stopped working). Connection to the database is straightforward - no TLS certificates or SSH is used, just the `postgresql://user:password@ip/database` connection string.

## What did you expect to happen?

I expected to connect to the database :)

## What actually happened?
After pressing 'Connect', following error appears under the name of database:
```
SSL error: certificate verify failed
SecCertificateCreateWithData() failed for certificate 0.
```

## What software versions are you using?

Postico version:  
`Version 1.5.14 (6816)`

macOS version:  
`11.0 Beta (20A5374i)`

PostgreSQL version:  
`PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by Debian clang version 10.0.1 , 64-bit`

## P.S.
I understand that something like this is expected when the beta version of OS is used, and that this might be an Apple-related issue.

**Comment by jakob** [comment] 2020-10-13 14:16
Thanks for reporting this.

This does look like a macOS error at first glance -- it seems that macOS can not decode the certificate. Looking at the code, the certificate should be in the correct format at that point, because otherwise OpenSSL should have reported an error.

Unfortunately, I can't test this on the same build you have. Connecting to servers with TLS certificates works as expected on build `20A5384c`, which is the latest build as I'm writing this.

Could you check if this bug still occurs on the latest beta?

**Comment by dasdy** [comment] 2020-10-20 13:54
My current version is `20A5395g`, and I'm still getting the issue.

**Comment by jakob** [comment] 2020-10-21 11:38
Thanks for trying again.

I've created a debug build of Postico 1.5 which you can download here:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7274.zip

This build writes a copy of the certificate to `~/Library/Containers/at.eggerapps.Postico/Data/Library/Application Support/Postico/certificate.0.DER` before trying to parse it with `SecCertificateCreateWithData()`.

Could you try downloading this build, and if it fails again, check the certificate file if there's something wrong with it? If you could email me a copy of the certificate file to postico@eggerapps.at that would be best.

**Comment by dasdy** [comment] 2020-10-22 19:40
Thank you for the reply, I've sent the files.

**Comment by jakob** [comment] 2020-10-28 09:07
Thanks for sending the files. I've confirmed that this is indeed a bug in Big Sur and have reported it to Apple.

As a workaround, you can try using Postico 2 (Download from https://eggerapps.at/postico2/).

In Postico 2, you can optionally provide a server certificate. If you do that, Postico will use libpq/OpenSSL to verify the certificate instead of the macOS Security Framework. Then you should be able to connect to the server.

**Comment by jakob** [comment] 2020-10-29 14:32
This bug persists in macOS 11.0.1 Beta. If Apple don't fix it we'll have to add a workaround.

**Comment by jakob** [comment] 2020-11-06 14:55
The bug persists in the macOS 11.0.1 Release Candidate, and there was no response from Apple. So I'm adding a workaround for the issue. The next version of Postico will detect the bug, and ask you if you want to connect without verifying the certificate.

Here's a debug build of Postico 1.5 with the workaround:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7338.zip

And here's a debug build of Postico 2 with the workaround:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7339.dmg

**Comment by dasdy** [comment] 2020-11-09 12:34
Thanks for implementing this. Both builds works on my machine, however, I think I'll stick with manually providing the server certificate for now.

**Comment by nlassaux** [comment] 2020-11-13 20:00
I have the same issue here. 

- Mac OS: version 11.0.1 (20B29)
- Postico: version 1.5.14 (6816)
 Error Message: ```
SSL error: certificate verify failed
SecCertificateCreateWithData() failed for certificate 0.
```

**Comment by jakob** [comment] 2020-11-13 20:53
@nlassaux Are you connecting to Google Cloud?

**Comment by nlassaux** [comment] 2020-11-16 17:38
> @nlassaux Are you connecting to Google Cloud?

Indeed, managed SQL from Google Cloud

**Comment by jakob** [comment] 2020-11-16 18:19
Postico 1.5.15 now shows a dialog and asks if you want to connect without verifying the certificate if macOS can't read it.

I hope that Apple eventually fixes this issue, but I have still received no feedback on my bug report.

To ensure the safety of your connection, I'd recommend to use an SSH tunnel to the database server if possible -- then verifying the TLS certificate is not necessary.

If you use Postico 2 Preview, you can manually provide the server certificate, in which case the authenticity will be verified with OpenSSL instead of the macOS security framework.

I'm closing this issue now. Thanks for taking the time to report this.

**Closed by jakob** 2020-11-16 18:19 UTC
